- id: '1628946413065'
  alias: Water Sensor Wet
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 457a0b5f2b117c3931e0d6e3b8547af8
    entity_id: binary_sensor.aqara_water_sensor_water_leak
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Water Sensor wet
      title: Home Assistant
  - service: notify.persistent_notification
    data:
      message: Water Sensor wet
      title: Sensor Alert
  mode: single
- id: '1631256431703'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 10
      time: 06:00:00
      day: 7
      exclude:
        entity_id: []
        device_id:
        - 876e673f882199fbe64d4c0cc5ea2bb7
        - 26ee004296d72bcdf636d2a855c4e27b
      actions:
      - device_id: 26ee004296d72bcdf636d2a855c4e27b
        domain: mobile_app
        type: notify
        title: HA battery alert
        message: device {{sensors}} low battery
- id: '1633400011306'
  alias: Sunrise Lights
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '-20'
  condition: []
  action:
  - scene: scene.sunrise
  mode: single
- id: '1640560137721'
  alias: Doorbell
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 37498442d18cbd950e943187e03d3684
    type: action
    subtype: bell1
    discovery_id: 0x0008890001d9a85f action_bell1
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: Doorbell beep boop!
      title: Home Assistant
  - service: notify.notify
    data:
      message: Doorbell beep boop
      title: Home Assistant
  mode: single
- id: '1640647620411'
  alias: Office Light Motion Detected
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.aqara_motion_sensor_occupancy
      light_target:
        device_id: 20d5d7cb30ac6372542d04e881afc7cd
        entity_id: light.wled_dig1
      no_motion_wait: 242
- id: '1641161831722'
  alias: 'Sunset Lights '
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-15'
  condition: []
  action:
  - scene: scene.sunset
  mode: single
- id: '1641320792111'
  alias: Tag Activate Sleep is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 3c7d13df-3ea3-436b-b896-f77976bbc07c
  condition: []
  action:
  - scene: scene.sleep
  mode: single
- id: '1641403112639'
  alias: Tag Office Lamp Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 726abc05-030f-4efe-88c3-06f79717b291
  condition: []
  action:
  - type: toggle
    device_id: 20d5d7cb30ac6372542d04e881afc7cd
    entity_id: light.office
    domain: light
  mode: single
- id: '1641538213733'
  alias: Aqara Magic Cube (Z2M)
  description: ''
  use_blueprint:
    path: luckypoppy/z2m-xiaomi-cube-controller.yaml
    input:
      remote: sensor.aqara_cube_action
      shake:
      - type: toggle
        device_id: 2391d4b99c1645ed27199951e9143406
        entity_id: switch.living_room
        domain: switch
- id: '1643610423725'
  alias: Sleep
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  - platform: state
    entity_id: scene.sleep
  condition: []
  action:
  - scene: scene.sleep
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.new_automation
  - service: notify.mobile_app_sm_g991u1
    data:
      message: Alarm Armed
  mode: single
- id: '1645164969169'
  alias: Alarm
  description: sensors turn on lights and notify
  trigger:
  - type: opened
    platform: device
    device_id: 52e226e5dab339338e2053cdc5b074b0
    entity_id: binary_sensor.aqara_guest_room_window_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - type: opened
    platform: device
    device_id: a6c26ab1de80d801bd3fc2c29bb4cf65
    entity_id: binary_sensor.aqara_kitchen_door_sensor_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - type: opened
    platform: device
    device_id: fbdb7e6e6d35e20770defe138269085a
    entity_id: binary_sensor.aqara_living_room_window_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - type: motion
    platform: device
    device_id: 3d6aa68c4d5d96258fbbd792fa63fb5c
    entity_id: binary_sensor.wireless_motion_sensor_occupancy
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: d97e516b46ac57f4fd053bb5d9b9da6e
    entity_id: binary_sensor.aqara_motion_sensor_occupancy
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_sm_g991u1
    data:
      message: Alarm
  - type: turn_on
    device_id: 2391d4b99c1645ed27199951e9143406
    entity_id: switch.living_room
    domain: switch
  - type: turn_on
    device_id: 20d5d7cb30ac6372542d04e881afc7cd
    entity_id: light.office
    domain: light
    brightness_pct: 100
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.yamie
  - service: media_player.turn_on
    data: {}
    target:
      entity_id: media_player.yamie
  - service: tts.google_translate_say
    data:
      entity_id: media_player.yamie
      message: Alarm
  mode: single
- id: '1645256644555'
  alias: Offline detection for Z2M devices with last_seen
  description: ''
  use_blueprint:
    path: Mr-Groch/offline-notification-for-sensors-with-last_seen.yaml
    input:
      time: 08:00:00
      actions:
      - service: notify.mobile_app_sm_g991u1
        data:
          message: Z2M sensor offline
- id: '1645509455183'
  alias: Disable Alarm (home)
  description: ''
  trigger:
  - platform: webhook
    webhook_id: workalarm2022
  - type: not_plugged_in
    platform: device
    device_id: 876e673f882199fbe64d4c0cc5ea2bb7
    entity_id: binary_sensor.pixel_3_is_charging
    domain: binary_sensor
  condition:
  - condition: zone
    entity_id: person.benjitimate
    zone: zone.home
  action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.new_automation
  - service: notify.mobile_app_sm_g991u1
    data:
      message: Alarm Disabled
      title: Home Assistant
  mode: single
- id: '1645944030427'
  alias: Tag Activate Sleep is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 3c7d13df-3ea3-436b-b896-f77976bbc07c
  condition: []
  action:
  - service: script.1645165207161
    data: {}
  mode: single
