- id: '1628946413065'
  alias: Water Sensor Wet
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 457a0b5f2b117c3931e0d6e3b8547af8
    entity_id: binary_sensor.aqara_water_sensor_water_leak
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Water Sensor wet
      title: Home Assistant
  - service: notify.persistent_notification
    data:
      message: Water Sensor wet
      title: Sensor Alert
  mode: single
- id: '1631256431703'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 10
      time: 06:00:00
      day: 7
      exclude:
        entity_id: []
        device_id:
        - 876e673f882199fbe64d4c0cc5ea2bb7
        - 26ee004296d72bcdf636d2a855c4e27b
      actions:
      - device_id: 26ee004296d72bcdf636d2a855c4e27b
        domain: mobile_app
        type: notify
        title: HA battery alert
        message: device {{sensors}} low battery
- id: '1633400011306'
  alias: Sunrise Lights
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '-20'
  condition: []
  action:
  - scene: scene.sunrise
  mode: single
- id: '1640560137721'
  alias: Doorbell
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 37498442d18cbd950e943187e03d3684
    type: action
    subtype: bell1
    discovery_id: 0x0008890001d9a85f action_bell1
  condition: []
  action:
  - type: turn_on
    device_id: b46041f984bbf37d86d7e020bd09ee72
    entity_id: light.front_door_light
    domain: light
    brightness_pct: 50
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - type: turn_on
    device_id: b46041f984bbf37d86d7e020bd09ee72
    entity_id: light.front_door_light
    domain: light
    brightness_pct: 5
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - type: turn_on
    device_id: b46041f984bbf37d86d7e020bd09ee72
    entity_id: light.front_door_light
    domain: light
    brightness_pct: 5
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - type: turn_on
    device_id: b46041f984bbf37d86d7e020bd09ee72
    entity_id: light.front_door_light
    domain: light
    brightness_pct: 50
  - service: notify.persistent_notification
    data:
      message: Doorbell beep boop!
      title: Home Assistant
  - service: notify.notify
    data:
      message: Doorbell beep boop
      title: Home Assistant
  - condition: sun
    before: sunset
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: turn_on
    device_id: b46041f984bbf37d86d7e020bd09ee72
    entity_id: light.front_door_light
    domain: light
    brightness_pct: 5
  - type: turn_off
    device_id: b46041f984bbf37d86d7e020bd09ee72
    entity_id: light.front_door_light
    domain: light
  mode: single
- id: '1640647620411'
  alias: Office Light Motion Detected
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.aqara_motion_sensor_occupancy
      light_target:
        device_id: 20d5d7cb30ac6372542d04e881afc7cd
      no_motion_wait: 242
- id: '1641161831722'
  alias: 'Sunset Lights '
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-15'
  condition: []
  action:
  - scene: scene.sunset
  mode: single
- id: '1641320792111'
  alias: Tag Activate Sleep is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 3c7d13df-3ea3-436b-b896-f77976bbc07c
  condition: []
  action:
  - scene: scene.sleep
  mode: single
- id: '1641403112639'
  alias: Tag Office Lamp Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 726abc05-030f-4efe-88c3-06f79717b291
  condition: []
  action:
  - type: toggle
    device_id: 20d5d7cb30ac6372542d04e881afc7cd
    entity_id: light.office
    domain: light
  mode: single
- id: '1641538213733'
  alias: Aqara Magic Cube (Z2M)
  description: ''
  use_blueprint:
    path: luckypoppy/z2m-xiaomi-cube-controller.yaml
    input:
      remote: sensor.aqara_cube_action
      shake:
      - type: toggle
        device_id: 2391d4b99c1645ed27199951e9143406
        entity_id: switch.living_room
        domain: switch
- id: '1641936119584'
  alias: 'Someone at Door '
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: d97e516b46ac57f4fd053bb5d9b9da6e
    entity_id: binary_sensor.aqara_motion_sensor_occupancy
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_sm_g991u1
    data:
      message: Door!
      title: Motion Detection
  - type: toggle
    device_id: 2391d4b99c1645ed27199951e9143406
    entity_id: switch.living_room
    domain: switch
  - type: toggle
    device_id: 20d5d7cb30ac6372542d04e881afc7cd
    entity_id: light.office
    domain: light
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: toggle
    device_id: 2391d4b99c1645ed27199951e9143406
    entity_id: switch.living_room
    domain: switch
  - type: toggle
    device_id: 20d5d7cb30ac6372542d04e881afc7cd
    entity_id: light.office
    domain: light
  mode: single
- id: '1643610423725'
  alias: Sleep
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - scene: scene.sleep
  mode: single
